import "./globals.css";
import { Inter } from "next/font/google";
import Layout from "@/components/Layout";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
    title: "ShopXpress",
    description: "Generated by create next app",
    icon: "https://cdn-icons-png.flaticon.com/512/712/712747.png",
};

export default function RootLayout({ children }) {
    return (
        <html lang="en">
            <head>
                <meta
                    name="viewport"
                    content="width=device-width, height=device-height, initial-scale=1.0, maximum-scale=1.0"
                />
            </head>
            <body suppressHydrationWarning={true} className={inter.className}>
                <Layout children={children} />
            </body>
        </html>
    );
}
